In [1]:
pip install pandas

Requirement already satisfied: pandas in /Users/mohinikathrotiya/Mohiniiiiiiiii/Python /Krish Naik- Udemy/venv/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /Users/mohinikathrotiya/Mohiniiiiiiiii/Python /Krish Naik- Udemy/venv/lib/python3.12/site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/mohinikathrotiya/Mohiniiiiiiiii/Python /Krish Naik- Udemy/venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/mohinikathrotiya/Mohiniiiiiiiii/Python /Krish Naik- Udemy/venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/mohinikathrotiya/Mohiniiiiiiiii/Python /Krish Naik- Udemy/venv/lib/python3.12/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /Users/mohinikathrotiya/Mohiniiiiiiiii/Python /Krish Naik- Udemy/venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [ ]:
# Series: is a 1D array like obj that can hold any data type,it is similar to a column in a table

data = [1,2,3,4,5]
series = pd.Series(data)
print('Series, \n', series)
print(type(series))

Series,
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
# Create a Series from dictionary
# Key will become index, and values will be series values
data  = {'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [7]:
data = [10, 20, 30]
index = ['a', 'b', 'c']

pd.Series(data, index = index)

a    10
b    20
c    30
dtype: int64

In [17]:
## DataFrame: 2D 
## Create a DF from dict of list

data = {
    'Name': ['John', 'Jack', 'Daniel'],
    'Age': [25, 36, 28],
    'City': ['NJ', 'Chicago', 'NY']

}
df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age     City
0    John   25       NJ
1    Jack   36  Chicago
2  Daniel   28       NY
<class 'pandas.core.frame.DataFrame'>

In [11]:
import numpy as np
np.array(data)

array({'Name': ['John', 'Jack', 'Daniel'], 'Age': [25, 36, 28], 'City': ['NJ', 'Chicago', 'NY']},
      dtype=object)

In [12]:
# Create a DF from list of dictionary, 

data = [
    {'Name': 'John', 'Age':36, 'City': 'NJ'},
    {'Name': 'John', 'Age':36, 'City': 'NJ'},
    {'Name': 'John', 'Age':36, 'City': 'NJ'},
    {'Name': 'John', 'Age':36, 'City': 'NJ'},
]

df = pd.DataFrame(data)
print(df)
print(type(df))

   Name  Age City
0  John   36   NJ
1  John   36   NJ
2  John   36   NJ
3  John   36   NJ
<class 'pandas.core.frame.DataFrame'>

In [14]:
df = pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [15]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [19]:
## Accessing data from DF

data
df

     Name  Age     City
0    John   25       NJ
1    Jack   36  Chicago
2  Daniel   28       NY

In [23]:
print(df['Name'])
type(df['Name'])

0      John
1      Jack
2    Daniel
Name: Name, dtype: object

pandas.core.series.Series

In [26]:
df.loc[0]

Name    John
Age       25
City      NJ
Name: 0, dtype: object

In [27]:
df.iloc[0]

Name    John
Age       25
City      NJ
Name: 0, dtype: object

In [33]:
print(df.loc[0][0])
print(df.iloc[0][0])

John
John

/var/folders/32/4gjfcmjd6sd493d4pqrg896c0000gn/T/ipykernel_52097/2433633864.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.loc[0][0])
/var/folders/32/4gjfcmjd6sd493d4pqrg896c0000gn/T/ipykernel_52097/2433633864.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[0][0])

In [37]:
df

     Name  Age     City
0    John   25       NJ
1    Jack   36  Chicago
2  Daniel   28       NY

In [36]:
## Accessing a specific element
df.at[1,'Age']

np.int64(36)

In [38]:
df.at[2, 'Name']

'Daniel'

In [39]:
## Accessing specified element using iat

df.iat[2, 2]

'NY'

In [43]:
## Data Manipulation with Data Frames
df['Salary'] = [50000, 65000, 78000]

In [44]:
df

     Name  Age     City  Salary
0    John   25       NJ   50000
1    Jack   36  Chicago   65000
2  Daniel   28       NY   78000

In [ ]:
## Remove a column

df.drop('Salary', axis=1) # even after this the salary column is there, as it does not save the changes

     Name  Age     City
0    John   25       NJ
1    Jack   36  Chicago
2  Daniel   28       NY

In [47]:
df

     Name  Age     City  Salary
0    John   25       NJ   50000
1    Jack   36  Chicago   65000
2  Daniel   28       NY   78000

In [48]:
df.drop('Salary', axis=1, inplace= True)

In [49]:
df

     Name  Age     City
0    John   25       NJ
1    Jack   36  Chicago
2  Daniel   28       NY

In [50]:
## add age to the column

df['Age'] = df['Age'] +1
df

     Name  Age     City
0    John   26       NJ
1    Jack   37  Chicago
2  Daniel   29       NY

In [51]:
df.drop(0)

     Name  Age     City
1    Jack   37  Chicago
2  Daniel   29       NY

In [52]:
df

     Name  Age     City
0    John   26       NJ
1    Jack   37  Chicago
2  Daniel   29       NY

In [53]:
df.drop(0, inplace=True)

In [54]:
df

     Name  Age     City
1    Jack   37  Chicago
2  Daniel   29       NY

In [55]:
df.describe()

             Age
count   2.000000
mean   33.000000
std     5.656854
min    29.000000
25%    31.000000
50%    33.000000
75%    35.000000
max    37.000000

In [56]:
sales = pd.read_csv('sales_data.csv')

In [57]:
sales.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [59]:
sales.dtypes

Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object